name: 🐳🐳🐳 Build and publish docker image 🐳🐳🐳

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build Docker Image for Unity ${{ matrix.unity.version }}
    strategy:
      fail-fast: false
      matrix:
        unity:
          - { version: "ubuntu-2021.3.19f1-linux-il2cpp-1" }
          - { version: "ubuntu-2021.3.24f1-linux-il2cpp-1" }
          - { version: "ubuntu-2021.3.40f1-linux-il2cpp-1" }
        coverage:
          - false
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - name: Clean up unused Docker resources
        run: docker system prune -af

      - name: Check disk space
        run: df -h

      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/readycodeio/readycode-docker-builder/editor:${{ matrix.unity.version }}
          file: Dockerfile-${{ matrix.unity.version }}
